---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(tidytext)
library(tm)
library(widyr)
library(glue)
```

```{r}
full_mpaa <- read.csv("../data/clean_mpaa_data.csv")
```


```{r}
#there are a few terms I do not want to be treated as separate words when dashes are removed
#also addressing some misspellings
full_mpaa <- full_mpaa %>% 
  #adding word count column, # words in the reason
  mutate(reason = str_trim(reason),
         reason_len = str_count(reason,"\\S+")) %>% 
  mutate(reason = str_replace(reason, "sci-fi", "scifi"),
         reason = str_replace(reason, "non-stop", "nonstop"),
         reason = str_replace(reason, "martial arts", "martialarts"),
         reason = str_replace(reason, "drug use", "druguse"),
         reason = str_replace(reason, "drug abuse", "drugabuse"),
         reason = str_replace(reason, "substance use", "substanceuse"),
         reason = str_replace(reason, "substance abuse", "substanceabuse"),
         reason = str_replace(reason, "PG-13", "PG13"),
         reason = str_replace(reason, "NC-17", "NC17"),
         reason = str_replace(reason, "langauge", "language"),
         reason = str_replace(reason, "languge", "language"),
         reason = str_replace(reason, "langugage", "language"),
         reason = str_replace(reason, "langage", "language"),
         reason = str_replace(reason, "sexuailty", "sexuality"),
         reason = str_replace(reason, "sexualtiy", "sexuality"),
         reason = str_replace(reason, "sexaul", "sexual")
  )
  
        

full_mpaa
```

```{r}
#saveRDS(full_mpaa, file = "../mpaa_rating_reasons_app/data/mpaa.rds")
```

```{r}
mpaa_stop_words <- tribble(
  ~word, ~lexicon,
  "rated", "CUSTOM",
  "pg", "CUSTOM",
  "pg13", "CUSTOM",
  "r",  "CUSTOM",
  "nc17", "CUSTOM",
  "for", "CUSTOM",
  "and", "CUSTOM",
  "a", "CUSTOM",
  "an", "CUSTOM",
  "of", "CUSTOM",
  "the", "CUSTOM",
  "including", "CUSTOM",
  "involving", "CUSTOM"
)

full_unigrams <- full_mpaa %>% 
  unnest_tokens(word, reason, drop = FALSE) %>% 
  anti_join(mpaa_stop_words)

#readjusting compound words
full_unigrams$reason <- str_replace(full_unigrams$reason, "martialarts", "martial arts")

full_unigrams$word <- str_replace(full_unigrams$word, "martialarts", "martial-arts")

full_unigrams$reason <- str_replace(full_unigrams$reason, "druguse", "drug use")

full_unigrams$word <- str_replace(full_unigrams$word, "druguse", "drug-use")

full_unigrams$reason <- str_replace(full_unigrams$reason, "scifi", "sci-fi")

full_unigrams$word <- str_replace(full_unigrams$word, "scifi", "sci-fi")
  
full_unigrams
```


```{r}
full_unigram_counts <- full_unigrams %>% 
  count(word) %>% 
  arrange(desc(n))

full_unigram_counts 
```

```{r}
mpaa_stop_words2 <- tribble(
  ~bigram, ~lexicon,
  "rated pg", "CUSTOM",
  "rated pg13", "CUSTOM",
  "rated nc17", "CUSTOM",
  "rated r", "CUSTOM",
  "pg13 for", "CUSTOM",
  "pg for", "CUSTOM",
  "r for",  "CUSTOM",
  "nc17 for", "CUSTOM",
  "and for", "CUSTOM",
  "and some", "CUSTOM",
  "for some", "CUSTOM",
  "and brief", "CUSTOM",
  "use and", "CUSTOM"
)
full_bigrams <- full_mpaa %>%
  unnest_tokens(bigram, reason, token = "ngrams", n = 2, drop = FALSE) %>%
  anti_join(mpaa_stop_words2) %>% 
  filter(!is.na(bigram))

full_bigrams$reason <- str_replace(full_bigrams$reason, "nonstop", "non-stop")

full_bigrams$bigram <- str_replace(full_bigrams$bigram, "nonstop", "non-stop")

full_bigrams$reason <- str_replace(full_bigrams$reason, "martialarts", "martial arts")

full_bigrams$bigram <- str_replace(full_bigrams$bigram, "martialarts", "martial arts")

full_bigrams
```

```{r}
full_bigram_counts <- full_bigrams %>% 
  count(bigram) %>% 
  arrange(desc(n))

full_bigram_counts 
```

```{r}
full_bigram_counts %>% 
  filter(grepl("violence", bigram))
```

```{r}
full_bigram_counts %>% 
  filter(grepl("language", bigram))
```

```{r}
full_word_cors <- full_unigrams%>%
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, X, sort = TRUE)

full_word_cors
```

```{r}
full_word_cors %>% 
  filter(item2 == "violence")
```

```{r}
full_word_cors %>% 
  filter(item2 == "language")
```

```{r}
#Practicing switching tidy text to DTM

full_dtm <- full_mpaa %>%
  unnest_tokens(word, reason) %>% 
  anti_join(mpaa_stop_words)%>%
  mutate(word = str_replace(word, "nonstop", "non-stop")) %>%
  mutate(word = str_replace(full_unigrams$word, "martialarts", "martial-arts")) %>%
  mutate(word = str_replace(full_unigrams$word, "martialarts", "drug-use")) %>%
  count(X, word) %>%
  cast_dtm(X, word, n)

full_dtm
```

```{r}
create_matrix <- function(rat1, rat2, year1, year2) {
  # filter for the ratings of interest
  rating1_df<- full_unigrams %>% 
    filter(rating == rat1,
           year >= year1,
           year <= year2)
  
  rating2_df<- full_unigrams %>% 
    filter(rating == rat2,
           year >= year1,
           year <= year2)
  
  # pull out the words for those ratings
  rating1_words <- paste(rating1_df$word,
                         collapse = " ")
  
  rating2_words <- paste(rating2_df$word,
                         collapse = " ")
  
  #create a TDM
  combined_tdm <- TermDocumentMatrix(VCorpus(VectorSource(c(rating1_words, rating2_words))))
  
  #name columns based on selected ratings
  colnames(combined_tdm) <- c(rat1, rat2)
  
  #convert to matrix
  combined_m <- as.matrix(combined_tdm)
  
}
```

```{r}
text_matrix <- create_matrix("PG", "NC-17", 2006, 2018)

comparison.cloud(text_matrix, colors = "steelblue1", max.words = 75)
```


```{r}
pg_unigrams <- full_unigrams %>% 
  filter(rating == "PG")

pg13_unigrams <- full_unigrams %>% 
  filter(rating == "PG-13")
```

```{r}
all_pg <- paste(pg_unigrams$word,
                collapse = " ")

all_pg13 <- paste(pg13_unigrams$word,
                  collapse = " ")

pg_pg13 <- c(all_pg, all_pg13)

pg_pg13_tdm <- TermDocumentMatrix(VCorpus(VectorSource(pg_pg13)))

colnames(pg_pg13_tdm) <- c("pg", "pg13")

pg_pg13_m <- as.matrix(pg_pg13_tdm)

comparison.cloud(pg_pg13_m, colors = c("orange", "blue"), max.words = 30)
```

```{r}
commonality.cloud(pg_pg13_m, colors = "steelblue1", max.words = 75)
```

```{r}
unique(str_subset(full_unigrams$word, "^sex"))
```

```{r}
unique(str_subset(full_unigrams$word, "^violen"))
```

```{r}
full_unigram_counts %>% filter(word == "sexuality")
```

```{r}
pg_counts <- pg_unigrams %>% 
  count(word, sort = TRUE)

pg_counts
```


```{r}
noun <- "action"
pattern <- glue("(?<=, |for )(.+ and)?([^,]*?{noun}[^,]*?)(.|,.+?| and.+?)$")

modifier_mpaa <- full_mpaa %>% 
  filter(grepl(noun, reason)) %>% 
  mutate(reason = str_trim(reason),
         modifiers = str_match(reason, pattern)[ ,3]) %>% 
  mutate(modifiers = str_trim(modifiers))

modifier_counts <- modifier_mpaa%>% 
  count(modifiers) %>% 
  arrange(desc(n))

modifier_counts
```

```{r}
modifier_stop_words <- tribble(
  ~word, ~lexicon,
  glue("{noun}"), "CUSTOM",
  "a", "CUSTOM",
  "an", "CUSTOM",
  "of", "CUSTOM",
  "the", "CUSTOM",
  "including", "CUSTOM",
  "involving", "CUSTOM"
)

modifier_mpaa <- modifier_mpaa %>% 
  unnest_tokens(word, modifiers, drop = FALSE) %>% 
  anti_join(modifier_stop_words)

modifier_mpaa$word <- str_replace(modifier_mpaa$word, "martialarts", "martial-arts")

modifier_mpaa$word <- str_replace(modifier_mpaa$word, "druguse", "drug-use")

modifier_mpaa$word <- str_replace(modifier_mpaa$word, "scifi", "sci-fi")

modifier_word_counts <- modifier_mpaa%>% 
  count(word) %>% 
  arrange(desc(n))

modifier_word_counts 
```

```{r}
modifier_counts_yr <- modifier_mpaa %>% 
  group_by(year) %>% 
  count(word) %>% 
  arrange(year)

modifier_counts_rating <- modifier_mpaa %>% 
  group_by(rating) %>% 
  count(word) %>% 
  arrange(rating)

modifier_counts_rating_yr <- modifier_mpaa %>% 
  group_by(rating, year) %>% 
  count(word) %>% 
  arrange(rating, year)

modifier_counts_rating_yr
```

```{r}
noun <- "action"
pattern <- glue("(?<=, |for )(.+ and)?([^,]*?{noun}[^,]*?)(.|,.+?| and.+?)$")

modifier_mpaa2 <- full_mpaa %>% 
  filter(grepl(noun, reason)) %>% 
  mutate(reason = str_trim(reason),
         modifiers = str_match(reason, pattern)[ ,3]) %>% 
  mutate(modifiers = if_else(grepl("and", modifiers), str_match(modifiers, "(?<=and )(.+)")[ ,2], modifiers)) 

modifier_mpaa2$modifiers
```


```{r}
letterCloud( pg_counts, word = "PG13", size = .5)
```

```{r}
full_mpaa %>% distinct(rating)
```

