---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(tidytext)
library(tm)
library(widyr)
library(glue)
```

```{r}
full_mpaa <- read.csv("../data/clean_mpaa_data.csv")
```


```{r}
#there are a few terms I do not want to be treated as separate words when dashes are removed
#also addressing some misspellings
full_mpaa <- full_mpaa %>% 
  #adding word count column, # words in the reason
  mutate(reason = str_trim(reason),
         reason_len = str_count(reason,"\\S+")) %>% 
  mutate(reason = str_replace(reason, "sci-fi", "scifi"),
         reason = str_replace(reason, "non-stop", "nonstop"),
         reason = str_replace(reason, "martial arts", "martialarts"),
         reason = str_replace(reason, "drug use", "druguse"),
         reason = str_replace(reason, "old fashioned", "oldfashioned"),
         reason = str_replace(reason, "risk-raking", "risktaking"),
         reason = str_replace(reason, "sado-masochistic", "sadomasochistic"),
         reason = str_replace(reason, "non-sexual", "nonsexual"),
         reason = str_replace(reason, "sex-ed", "sexed"),
         reason = str_replace(reason, "PG-13", "PG13"),
         reason = str_replace(reason, "NC-17", "NC17"),
         reason = str_replace(reason, "langauge", "language"),
         reason = str_replace(reason, "languge", "language"),
         reason = str_replace(reason, "lanugage", "language"),
         reason = str_replace(reason, "langage", "language"),
         reason = str_replace(reason, "sexuailty", "sexuality"),
         reason = str_replace(reason, "sexualtiy", "sexuality"),
         reason = str_replace(reason, "sexaul", "sexual"),
         reason = str_replace(reason, "acton", "action"),
         reason = str_replace(reason, "disturrbing", "disturbing"),
         reason = str_replace(reason, "disurbing", "disturbing"),
         reason = str_replace(reason, "disturbung", "disturbing"),
         reason = str_replace(reason, "ganster", "gangster"),
         reason = str_replace(reason, "matieral", "material"),
         reason = str_replace(reason, "relatedd", "related"),
         reason = str_replace(reason, "Rted", "Rated"),
         reason = str_replace(reason, "scatalogical", "scatological"),
         reason = str_replace(reason, "youg", "young"),
         reason = str_replace(reason, "prision", "prison"),
         reason = str_replace(reason, "pre-teen", "preteen"),
         reason = str_replace(reason, "teror", "terror")
         
  )
  
        

full_mpaa <- full_mpaa %>% 
  select('title', 'rating', 'reason', 'year', 'reason_len')

full_mpaa
```

```{r}
#saveRDS(full_mpaa, file = "../mpaa_rating_reasons_app/data/mpaa.rds")
```

```{r}
mpaa_stop_words <- tribble(
  ~word, ~lexicon,
  "rated", "CUSTOM",
  "pg", "CUSTOM",
  "pg13", "CUSTOM",
  "r",  "CUSTOM",
  "nc17", "CUSTOM",
  "for", "CUSTOM",
  "and", "CUSTOM",
  "a", "CUSTOM",
  "an", "CUSTOM",
  "of", "CUSTOM",
  "the", "CUSTOM",
  "including", "CUSTOM",
  "involving", "CUSTOM"
)

full_unigrams <- full_mpaa %>% 
  unnest_tokens(word, reason, drop = FALSE) %>% 
  anti_join(mpaa_stop_words) %>% 
  mutate(word = str_replace(word, "martialarts", "martial-arts"),
         word = str_replace(word, "druguse", "drug-use"),
         word = str_replace(word, "scifi", "sci-fi"),
         word = str_replace(word, "sexed", "sex-ed"),
         word = str_replace(word, "oldfashioned", "old-fashioned"),
         word = str_replace(word, "risktaking", "risk-taking")
         )

  
full_unigrams %>%
  filter(word == 'pre')
```


```{r}
full_unigram_counts <- full_unigrams %>%
  count(word) %>% 
  arrange(desc(n))

full_unigram_counts 
```

```{r}
str_remove("scenes", "s")
```



```{r}
singleton_words <- full_unigrams %>%
  count(word) %>% 
  filter(n == 1) %>% 
  select(word)

singleton_words
```

```{r}
full_singletons <- full_unigrams %>% 
  filter(word %in% singleton_words$word) 
```

```{r}
col_pal <- c("G" = "#1A9850", 
             "PG" = "#D9EF8B", 
             "PG-13" = "#FEE08B", 
             "R" = "#F46D43", 
             "NC-17" = "#A50026")
```

```{r}
full_singletons %>% 
  group_by(rating) %>% 
  summarize(`Unique words` = n_distinct(word),
            Movies = n_distinct(title))%>% 
  arrange(rating) %>% 
  pivot_longer(!rating, names_to = "variable",
               values_to = "count")
```


```{r}
full_singletons %>% 
  group_by(rating) %>% 
  summarize(`Individual Unique Words` = n_distinct(word),
            `Movie Rating Reasons` = n_distinct(title))%>% 
  arrange(rating) %>% 
  pivot_longer(!rating, names_to = "variable",
               values_to = "count") %>%  
  ggplot() +
  geom_col(aes(x = rating, y = count, fill = rating)
            ) +
  facet_grid(variable ~ .) +
   scale_fill_manual(values = col_pal
                    ) +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank()) +
  labs(title = "Unique word trends follow overall rating trends", 
       y = "",
       fill = "Rating",
       x = "")
```

```{r}
full_singletons %>% 
  group_by(year) %>% 
  summarize(`Individual Words` = n_distinct(word),
            `Movie Rating Reasons` = n_distinct(title))%>%
  arrange(year) %>% 
  pivot_longer(!year, names_to = "variable",
               values_to = "count")%>% 
  ggplot() +
  geom_line(aes(x = year, y = count, color = variable),
            size = .75,
            ) +
  geom_point(aes(x = year, y = count, color = variable),
            size = 1.5,
            ) +
  scale_color_manual(values = c('#9EDCDA', '#8856A7')) +
  theme_bw() +
  theme(panel.grid.minor.x = element_blank()) +
  scale_x_continuous(breaks = c(1990, 1995, 2000, 2005, 2010, 2015, 2020)) +
  labs(title = "Mid Nineties were the Height of Unique Words in MPAA Rating Reasons", 
       y = "Number",
       color = "",
       x = "")
```
```{r}
noun <- "language"

full_singletons %>% 
  filter(grepl(noun, reason)) %>% 
  group_by(title, rating, reason, year) %>% 
  count(title) %>% 
  arrange(desc(n)) %>% 
  select(Title = title, 
         Rating = rating, 
         `Year Rated` = year, 
         `Rating Reason` = reason,
         `Unique Words` = n)

```




```{r}
full_singletons %>% 
  select(title, reason_len) %>% 
  distinct() %>% 
  summarize(mean_len = mean(reason_len))
```

```{r}
full_singletons %>% 
  group_by(title, reason) %>% 
  count(title) %>% 
  arrange(desc(n))
```


```{r}
singleton_movies <- full_singletons %>% 
  select(title) %>% 
  distinct()
```

```{r}
full_unigrams %>% 
  filter(title %in% singleton_movies$title) %>% 
  count(word) %>% 
  arrange(desc(n))

```


```{r}
unique(str_subset(full_unigrams$word, "^sex"))
```

```{r}
unique(str_subset(full_unigrams$word, "^violen"))
```

```{r}
full_unigram_counts %>% filter(word == "sexuality")
```


```{r}
noun <- "action"
pattern <- glue("(?<=, |for )(.+ and)?([^,]*?{noun}[^,]*?)(.|,.+?| and.+?)$")

modifier_mpaa <- full_mpaa %>% 
  filter(grepl(noun, reason)) %>%
  mutate(reason = str_replace(reason, "martialarts", "martial arts"),
             reason = str_replace(reason, "druguse", "drug use"),
             reason = str_replace(reason, "drugabuse", "drugabuse"),
             reason = str_replace(reason, "substanceabuse", "substance abuse"),
             reason = str_replace(reason, "substanceuse", "substance use"),
             reason = str_replace(reason, "scifi", "sci-fi")) %>% 
  mutate(reason = str_trim(reason),
         modifiers = str_match(reason, pattern)[ ,3]) %>% 
  mutate(modifiers = str_trim(modifiers))

modifier_mpaa%>% 
  count(modifiers) %>% 
      mutate(mod_count = n) %>% 
      slice_max(mod_count, n=10) %>% 
      arrange(desc(n)) %>% 
        ggplot(aes(x = mod_count, y= modifiers)) +
        geom_col()


```

```{r}
modifier_stop_words <- tribble(
  ~word, ~lexicon,
  glue("{noun}"), "CUSTOM",
  "a", "CUSTOM",
  "an", "CUSTOM",
  "of", "CUSTOM",
  "the", "CUSTOM"
  #,
  # "including", "CUSTOM",
  # "involving", "CUSTOM"
)

modifier_tokens <- modifier_mpaa %>%
  mutate(modifiers = str_replace(modifiers, "sci-fi", "scifi")) %>% 
  unnest_tokens(word, modifiers) %>% 
  anti_join(modifier_stop_words)

modifier_tokens$word <- str_replace(modifier_tokens$word, "scifi", "sci-fi")

modifier_word_counts <- modifier_tokens%>% 
  count(word) %>% 
  arrange(desc(n))

modifier_word_counts 
```

```{r}
modifier_counts_yr <- modifier_mpaa %>% 
  group_by(year) %>% 
  count(word) %>% 
  arrange(year)

modifier_counts_rating <- modifier_mpaa %>% 
  group_by(rating) %>% 
  count(word) %>% 
  arrange(rating)

modifier_counts_rating_yr <- modifier_mpaa %>% 
  group_by(rating, year) %>% 
  count(word) %>% 
  arrange(rating, year)

modifier_counts_rating_yr
```

```{r}
noun <- "action"
pattern <- glue("(?<=, |for )(.+ and)?([^,]*?{noun}[^,]*?)(.|,.+?| and.+?)$")

modifier_mpaa2 <- full_mpaa %>% 
  filter(grepl(noun, reason)) %>% 
  mutate(reason = str_trim(reason),
         modifiers = str_match(reason, pattern)[ ,3]) %>% 
  mutate(modifiers = if_else(grepl("and", modifiers), str_match(modifiers, "(?<=and )(.+)")[ ,2], modifiers)) 

modifier_mpaa2$modifiers
```

```{r}

```

